name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files.
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment.
        value: ${{ jobs.deploy.outputs.outcome }}
    secrets:
      some-secret:
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Complile s3 deploy action
        run: |
          npm install -g @vercel/ncc
          cd ./.github/actions/deploy-s3-javascript
          npm install && ncc build main.js
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ./dist
      - name: Output files
        run: ls -l .
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Deploy site to S3
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          dry-run: 'true'
          bucket: gha-custom-action-hosting
          dist-folder: ./dist
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
