name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use React Application
        run: cd react-app # Change to the React application directory
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
