name: GitHub Actions for React App
on:
  pull_request:
    types: [opened, edited, closed]
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'react-app/**'
      - '.github/workflows/react-app.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --prefix react-app
      - name: Lint code
        run: npm run lint --prefix react-app
      - name: Test code
        run: npm run test --prefix react-app
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --prefix react-app
      - name: Build website
        run: npm run build --prefix react-app
      - name: Publish JS filename
        id: publish
        run: |
          cd react-app
          find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: react-app/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output files
        run: ls -l .
      - name: Output filename
        run: echo ${{ needs.build.outputs.script-file }}
      - name: Deploy
        run: echo "Deploying..."
