name: GitHub Actions for React App
on:
  pull_request:
    types: [opened, edited, closed]
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'react-app/**'
      - '.github/workflows/react-app.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefix react-app
      - name: Lint code
        run: npm run lint --prefix react-app
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefix react-app
      - name: Test code
        id: run-tests
        run: npm run test --prefix react-app
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: react-app/test.json
  build:
    needs: test
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 18]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefix react-app
      - name: Build website
        id: build-website
        run: npm run build --prefix react-app
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: react-app/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output files
        run: ls -l .
      - name: Deploy
        run: echo "Deploying..."
  report:
    runs-on: ubuntu-latest
    needs: [lint, deploy]
    if: failure()
    steps:
      - name: Output information
        run: |
          echo "Something went wrong!"
          echo "${{ toJson(github) }}"
