name: GitHub Actions for React App
on:
  pull_request:
    types: [opened, edited, closed]
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'react-app/**'
      - '.github/workflows/react-app.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: chached-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
      - name: Output information
        run: echo "Cache used? ${{ steps.chached-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint --prefix react-app
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test --prefix react-app
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: react-app/test.json
  build:
    needs: test
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        id: build-website
        run: npm run build --prefix react-app
      - name: Upload artifacts
        if: success() && matrix.operating-system == 'ubuntu-latest' && matrix.node-version == 18
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: react-app/dist
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: dist-files
    # secrets:
    #   some-secret: ${{ secrets.SOME_SECRET }}
  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: echo "${{ needs.deploy.outputs.result }}"
  report:
    runs-on: ubuntu-latest
    needs: [lint, deploy]
    if: failure()
    steps:
      - name: Output information
        run: |
          echo "Something went wrong!"
          echo "${{ toJson(github) }}"
