name: GitHub Actions for React App
on:
  pull_request:
    types: [opened, edited, closed]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --prefix react-app
      - name: Run tests
        run: npm test --prefix react-app
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --prefix react-app
      - name: Build project
        run: npm run build --prefix react-app
      - name: Deploy
        run: echo "Deploying..."
